import { AbaRegisterValidateTechnicalFeasibilityRequestDto } from './aba-register-validate-technical-feasibility-request.dto';
import { IGetDHCPDataResponse } from 'src/raw/boss-api/get-dhcp-data/get-dhcp-data-response.interface';
import { IGetDSLCentralCoIdByDSLAMPortIdResponse } from 'src/raw/database/functions/get-dsl-central-coid-by-dslam-port-id/get-dsl-central-coid-by-dslam-port-id-response.interface';
import { IGetValidVPIResponse } from 'src/raw/database/functions/get-valid-vpi/get-valid-vpi-response.interface';
import { IIsOccupiedPortResponse } from 'src/raw/database/stored-procedures/Is-occupied-port/is-occupied-port-response.interface';
import { ICheckIpResponse } from 'src/raw/database/stored-procedures/check-ip/check-ip-response.interface';
import { IDeleteOrderResponse } from 'src/raw/database/stored-procedures/delete-order/delete-order-response.interface';
import { IGetAbaDataFromRequestsResponse } from 'src/raw/database/stored-procedures/get-aba-data-from-requests/get-aba-data-from-requests-response.interface';
import { IGetAbaDataResponse } from 'src/raw/database/stored-procedures/get-aba-data/get-aba-data-response.interface';
import { IGetAndRegisterQualifOfServiceResponse } from 'src/raw/database/stored-procedures/get-and-register-qualif-of-service/get-and-register-qualif-of-service-response.interface';
import { IGetDataFromDSLAMPortIdResponse } from 'src/raw/database/stored-procedures/get-data-from-dslam-port-id/get-data-from-dslam-port-id-response.interface';
import { IGetDownstreamFromPlanResponse } from 'src/raw/database/stored-procedures/get-downstream-from-plan/get-downstream-from-plan-response.interface';
import { IGetPortIdFromIpResponse } from 'src/raw/database/stored-procedures/get-port-id-from-ip/get-port-id-from-ip-response.interface';
import { IGetPortIdResponse } from 'src/raw/database/stored-procedures/get-port-id/get-port-id-response.interface';
import { IInsertDslAbaRegistersResponse } from 'src/raw/database/stored-procedures/insert-dsl-aba-registers/insert-dsl-aba-registers-response.interface';
import { IIsPrepaidVoiceLineResponse } from 'src/raw/database/stored-procedures/is-prepaid-voice-line/is-prepaid-voice-line-response.interface';
import { IIsValidIpAddressResponse } from 'src/raw/database/stored-procedures/is-valid-ip-address/is-valid-ip-address-response.interface';
import { IReadIABAOrderResponse } from 'src/raw/database/stored-procedures/read-iaba-order/read-iaba-order-response.interface';
import { IVerifyContractByPhoneResponse } from 'src/raw/database/stored-procedures/verify-contract-by-phone/verify-contract-by-phone-response.interface';
import { ILinkNetworkResponse } from 'src/raw/pic/get-asap-order-detail/Iink-network-response.interface';
import { IGetASAPOrderDetailResponse } from 'src/raw/pic/get-asap-order-detail/get-asap-order-detail-response.interface';

export interface IAbaRegisterValidateTechnicalFeasibilityResponse {
  requestDto: AbaRegisterValidateTechnicalFeasibilityRequestDto;
  insertDslAbaRegistersResponse: IInsertDslAbaRegistersResponse;
  isPrepaidVoiceLine: IIsPrepaidVoiceLineResponse;
  getAndRegisterQualifOfServiceResponse: IGetAndRegisterQualifOfServiceResponse;
  verifyContractByPhoneResponse: IVerifyContractByPhoneResponse;
  getDownstreamFromPlanResponse: IGetDownstreamFromPlanResponse;
  getABADataFromRequestsResponse: IGetAbaDataFromRequestsResponse;
  isValidIpAddressResponse: IIsValidIpAddressResponse;
  getPortIdFromIpResponse: IGetPortIdFromIpResponse;
  queryDHCPResponse: IGetDHCPDataResponse;
  getValidVPIResponse: IGetValidVPIResponse;
  getPortIdResponse: IGetPortIdResponse;
  isOccupiedPortResponse: IIsOccupiedPortResponse;
  getASAPOrderDetailResponse: IGetASAPOrderDetailResponse;
  linkNetworkResponse: ILinkNetworkResponse;
  getABADataResponse: IGetAbaDataResponse;
  checkIpResponse: ICheckIpResponse;
  getDataFromDslamPortIdResponse: IGetDataFromDSLAMPortIdResponse;
  deleteOrderResponse: IDeleteOrderResponse;
  readIABAOrderResponse: IReadIABAOrderResponse;
  getDSLCentralCoIdByDSLAMPortIdResponse: IGetDSLCentralCoIdByDSLAMPortIdResponse;
}
