export enum CheckIpStatusConstants {
  SUCCESSFULL,
  ERROR,
  PORT_NOT_FOUND_BY_PHONE_NUMBER = 5,
  PORT_NOT_FOUND_BY_PARAMETER = 6,
  SUCCESSFULL_BY_BUSSINESS_LOGIC = 7,
  THERE_IS_NOT_CONTRACT_ASSOCIATED_WITH_THE_PORT = 8,
  THE_PORT_IS_RESERVED = 9,
  THE_PORT_IS_OCCUPIED_BY_ANOTHER_CONTRACT = 10,
}
